CREATE DATABASE IF NOT EXISTS MN;

CREATE TABLE IF NOT EXISTS CONTROLLER (
    CONTROLLER_ID INT PRIMARY KEY,
    NAME VARCHAR( 100 ) NOT NULL
); 

CREATE TABLE IF NOT EXISTS LOCATION_AREA (
	  LOCATION_AREA_ID INT PRIMARY KEY,
	  CONTROLLER_ID INT NOT NULL,
    NAME VARCHAR( 100 ) NOT NULL,  
    FOREIGN KEY ( CONTROLLER_ID ) REFERENCES CONTROLLER( CONTROLLER_ID ) 
);  

CREATE TABLE IF NOT EXISTS CELL (
    CELL_ID INT PRIMARY KEY,
    LOCATION_AREA_ID INT NOT NULL,
    NAME VARCHAR( 100 ) NOT NULL,  
    FOREIGN KEY ( LOCATION_AREA_ID ) REFERENCES LOCATION_AREA( LOCATION_AREA_ID )
); 

CREATE TABLE IF NOT EXISTS SECTOR (
	  SECTOR_ID INT PRIMARY KEY,
    CELL_ID INT NOT NULL,
    NAME VARCHAR( 100 ) NOT NULL,  
    TYPE VARCHAR( 100 ) NOT NULL,  
    AZIMUTH VARCHAR( 100 ) NOT NULL,
    FOREIGN KEY ( CELL_ID ) REFERENCES CELL( CELL_ID )
); 